export const BACKEND_BASE_URL = "http://localhost:5001" 
export const LOGIN_URL = "/login"
export const PLAYLIST_URL = "/playlists"
export const SONG_URL = "/songs"
export const HOME_URL = "/home"
export const ALBUM_URL = "/albums"
export const ARTIST_URL = "/artists"
